export const INCH_TO_METER = 0.0254;
export const FOOT_TO_METER = 0.3048;
export const POUND_TO_KILOGRAM = 0.45359237;

const REGULATION_LANE_WIDTH_INCHES = 41.5;
const HEAD_PIN_DISTANCE_FEET = 60;
const LANE_END_DISTANCE_FEET = 62.849;
const REGULATION_GUTTER_WIDTH_INCHES = 9.25;
const MAX_BALL_DIAMETER_INCHES = 8.5;
const MAX_BALL_WEIGHT_POUNDS = 16;
const PIN_HEIGHT_INCHES = 15;
const PIN_MAX_DIAMETER_INCHES = 4.75;
const PIN_BASE_DIAMETER_INCHES = 2.25;
const PIN_SPACING_INCHES = 12;
const PIN_WEIGHT_POUNDS = 3.5;
const BALL_WALL_CLEARANCE_METERS = 0.015;
const BALL_START_Z_METERS = 0.82;
const EQUILATERAL_TRIANGLE_HEIGHT_RATIO = Math.sqrt(3) * 0.5;

export const BOWLING_DIMENSIONS = {
  laneWidth: REGULATION_LANE_WIDTH_INCHES * INCH_TO_METER,
  laneLengthToHeadPin: HEAD_PIN_DISTANCE_FEET * FOOT_TO_METER,
  laneEndFromFoulLine: LANE_END_DISTANCE_FEET * FOOT_TO_METER,
  gutterWidth: REGULATION_GUTTER_WIDTH_INCHES * INCH_TO_METER,
  ballDiameter: MAX_BALL_DIAMETER_INCHES * INCH_TO_METER,
  ballMassKg: MAX_BALL_WEIGHT_POUNDS * POUND_TO_KILOGRAM,
  pinHeight: PIN_HEIGHT_INCHES * INCH_TO_METER,
  pinMaxDiameter: PIN_MAX_DIAMETER_INCHES * INCH_TO_METER,
  pinBaseDiameter: PIN_BASE_DIAMETER_INCHES * INCH_TO_METER,
  pinSpacing: PIN_SPACING_INCHES * INCH_TO_METER,
  pinMassKg: PIN_WEIGHT_POUNDS * POUND_TO_KILOGRAM,
} as const;

export const BALL_RADIUS = BOWLING_DIMENSIONS.ballDiameter / 2;
export const PIN_MAX_RADIUS = BOWLING_DIMENSIONS.pinMaxDiameter / 2;
export const PIN_BASE_RADIUS = BOWLING_DIMENSIONS.pinBaseDiameter / 2;
export const LANE_HALF_WIDTH = BOWLING_DIMENSIONS.laneWidth / 2;
export const SAFE_BALL_LANE_OFFSET = LANE_HALF_WIDTH - BALL_RADIUS - BALL_WALL_CLEARANCE_METERS;
export const BALL_START_Z = BALL_START_Z_METERS;
export const HEAD_PIN_Z = -BOWLING_DIMENSIONS.laneLengthToHeadPin;
export const LANE_CENTER_Z = -BOWLING_DIMENSIONS.laneEndFromFoulLine / 2;
export const PIN_ROW_Z_SPACING = BOWLING_DIMENSIONS.pinSpacing * EQUILATERAL_TRIANGLE_HEIGHT_RATIO;
