export const INPUT_TUNING = {
  defaultLaneOffset: 0,
  defaultAngleRadians: 0,
  defaultPower: 0.7,
  defaultCurve: 0,
  keyboardLaneStepMeters: 0.08,
  keyboardAngleStepRadians: 0.035,
  minAngleRadians: -0.35,
  maxAngleRadians: 0.35,
  minPower: 0.35,
  maxPower: 1,
  minCurve: -0.6,
  maxCurve: 0.6,
} as const;

export const TIMING_TUNING = {
  throwReleaseDelayMs: 850,
  rivalThinkDelayMs: 850,
  resultDisplayMs: 1600,
  powerWaveCyclesPerSecond: 0.92,
  curveWaveRadiansPerSecond: Math.PI * 1.35,
  curveMeterMax: 0.6,
} as const;

export const UI_TUNING = {
  spriteThrowAnimationMs: 1150,
} as const;

export const RIVAL_TUNING = {
  accuracy: 0.78,
  power: 0.84,
  curveBias: 0.08,
  baseRisk: 0.08,
  pressurePerFrame: 0.018,
  pressurePerThrow: 0.015,
  wobbleScale: 0.3,
  riskPush: 0.035,
  laneAimCenterMeters: -0.16,
  laneRandomRangeMeters: 0.24,
  baseAngleRadians: 0,
  riskAngleScale: 0.18,
  powerRandomRange: 0.1,
  minPower: 0.5,
  maxPower: 1,
  curveRandomRange: 0.2,
  laneLimitMeters: 0.8,
  angleLimitRadians: 0.24,
  curveLimit: 0.45,
} as const;

export const PHYSICS_TUNING = {
  gravityY: -9.81,
  ballRestHeightMeters: 0.015,
  ballLinearDamping: 0.24,
  ballAngularDamping: 0.12,
  ballFriction: 0.62,
  ballRestitution: 0.2,
  throwBaseSpeedMetersPerSecond: 6.5,
  throwPowerSpeedMetersPerSecond: 4.5,
  throwCurveSideVelocity: 0.45,
  ballBackspinBase: -38,
  ballBackspinPerPower: -32,
  ballCurveSpinY: 6,
  ballCurveSpinZ: -10,
  curveImpulseFromSpin: 0.0008,
  curveImpulseMinimum: 0.0001,
  curveStopsBeforeHeadPinMeters: 1.5,
  pitSlowdownStartsAfterHeadPinMeters: -1.2,
  pitFallY: -0.5,
  pitSlowdownMultiplier: 0.94,
  settleMinimumMs: 1800,
  settleMaximumMs: 7200,
  settleStablePinsMs: 650,
  settledBallSpeed: 0.3,
  settledPinLinearSpeed: 0.18,
  settledPinAngularSpeed: 0.28,
  laneSurfaceY: -0.04,
  laneColliderHalfHeightMeters: 0.04,
  laneFriction: 0.5,
  gutterSurfaceY: -0.16,
  gutterColliderHalfHeightMeters: 0.04,
  gutterFriction: 0.86,
  sideWallExtraOffsetMeters: 0.04,
  sideWallY: -0.02,
  sideWallHalfWidthMeters: 0.035,
  sideWallHalfHeightMeters: 0.12,
  sideWallFriction: 0.8,
  pitZOffsetMeters: 0.8,
  pitY: -0.28,
  pitHalfWidthMeters: 1.15,
  pitHalfHeightMeters: 0.08,
  pitHalfDepthMeters: 0.85,
  pitFriction: 0.95,
  pitBackYOffsetMeters: 0.12,
  pitBackZOffsetMeters: 1.05,
  pitBackHalfHeightMeters: 0.28,
  pitBackHalfDepthMeters: 0.08,
  pitBackRestitution: 0.05,
  pinRestHeightMeters: 0.01,
  pinLinearDamping: 0.08,
  pinAngularDamping: 0.08,
  pinFriction: 0.74,
  pinRestitution: 0.38,
  pinUprightThreshold: 0.72,
  pinDownHeightRatio: 0.34,
} as const;

export const SCENE_TUNING = {
  cameraFovDegrees: 42,
  cameraNearMeters: 0.1,
  cameraFarMeters: 80,
  maxDevicePixelRatio: 2,
  fogNearMeters: 18,
  fogFarMeters: 34,
  aimingArrowLengthMeters: 3.4,
  aimingArrowY: 0.025,
  aimingLineRadiusMeters: 0.026,
  aimingHeadRadiusMeters: 0.105,
  aimingHeadLengthMeters: 0.28,
  laneMarkerY: 0.018,
  laneMarkerRadiusMultiplier: 1.7,
  laneMarkerTubeMeters: 0.008,
  idleCameraY: 0.5,
  idleCameraZ: 2.2,
  rollingCameraY: 0.42,
  rollingCameraBallXScale: 0.72,
  rollingCameraTargetXScale: 0.9,
  rollingCameraAheadMeters: 0.45,
  rollingCameraMinZFromHeadPinMeters: 0.85,
  rollingCameraMaxZ: 0.74,
  rollingCameraLerp: 0.16,
  settlingCameraY: 1.35,
  settlingCameraZFromHeadPinMeters: 2.0,
  settlingCameraLerp: 0.08,
  idleCameraLerp: 0.08,
  cameraLookAtY: 0.18,
  signageCanvasWidth: 1024,
  signageCanvasHeight: 256,
  signagePlaneWidthMeters: 4.5,
  signagePlaneHeightMeters: 1.12,
  signageMessageMaxChars: 28,
} as const;
